### PR TITLE
Utilities to parse the database logs

### PR DESCRIPTION
**Pull request by gperonato**
This is a docker service to parse the logs of the database. The parsed log is saved as a csv file.
The `db` service is also modified by this PR, as a custom configuration file has to be added.

### CODE REVIEW

**Review by neodark — APPROVED** [review]

**Comment by neodark** [comment]
@gperonato : can you solve this conflict so I can merge this one too ?

**Comment by neodark** [comment]
It should be straight-forward but I let you check first:
```
<<<<<<< stats
  stats:
    build:
      context: ./stats
    volumes:
      - ./stats:/stats
      - db-data:/db-data
=======
  db-nginx:
    build:
      context: ./db-nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - data:/usr/share/nginx/html/raster

  postgrest:
    build:
      context: ./postgrest
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
      - .postgrest

>>>>>>> master
```

**Comment by gperonato** [comment]
> @gperonato : can you solve this conflict so I can merge this one too ?

Done, thank you.

**Comment by neodark** [comment]
> > @gperonato : can you solve this conflict so I can merge this one too ?
> 
> Done, thank you.

Thanks will merge now :+1:

**Pull request merged**
