### PR TITLE
Integration pipeline for  hotmaps tabular

### PR DESCRIPTION
**Pull request by gperonato**

### CODE REVIEW

**Comment by neodark** [comment]
Same comment as https://github.com/enermaps/enermaps/pull/269#issuecomment-895923437
Please rebase on master this PR.
Take into account that the db stuff has been split in a separate docker-compose for more clarity. The README in data-integration with this PR needs to be updated accordingly and re-tested if it still works. (There's now a `-f ../docker-compose-db.yml` before the python script to run)

**Comment by neodark** [comment]
In: https://github.com/enermaps/enermaps/pull/271/files they were also modifications in :

- datasets.csv
- utilities.py

But not here. Did you forget to update those files in this PR or is it fine like this ?

**Comment by neodark** [comment]
I guess the conflicts is related to a rebase here. Let me know when you solved the issue for the merge.

**Comment by gperonato** [comment]
Yes, it has been rebased now.

**Review by neodark — APPROVED** [review]

**Pull request merged**
